export const ROLE = {
  ADMIN: "ADMIN",
  PROVIDER: "PROVIDER",
  TRADER: "TRADER",
  BUYER: "BUYER",
};

export const STATE = {
  OWNED: "OWNED",
  TRANSFERED: "TRANSFERED",
};

export const REQUEST_STATUS = {
  INREVIEW: "INREVIEW",
  GRANTED: "GRANTED",
  REJECTED: "REJECTED",
  TRANSFERD: "TRANSFERED",
};

export const ENCRYPTION = {
  AES: "AES",
  RSA: "RSA",
};

export const NETWORK = {
  LIVENET: "LIVENET",
  TESTNET: "TESTNET",
};

export const ACTIONS = {
  DELETE: "DELETE",
  ACCEPT: "ACCEPT",
  TRANSFER: "TRANSFER",
  VIEW: "VIEW",
};
