# Use an official Node.js runtime as a parent image
FROM node:14-alpine

# Set the working directory to /app
WORKDIR /app

# Copy the package.json and package-lock.json files into the container
COPY package*.json ./

# Install any needed packages specified in package.json
RUN npm install --no-optional --production

# Copy the rest of the application code into the container
COPY . .

# Expose the port that the server will be listening on
EXPOSE 9000

# Run the server
CMD ["npm run", "dev"]
